# Site settings
baseurl: "" # /gh-pages
asseturl: "/assets"
skin: "minifi"

# langsite
lang:
 brandname: "yzazy"
 read_more: ">>"
 showpostby: "danh mục: "
 postincat: "cùng mục"
 postintag: "cùng thẻ"
 ghim: "nổi bật"

# Build settings
markdown: kramdown
permalink: /:categories/:title
paginate: 12
paginate_path: /page:num

gems: [jekyll-paginate]
